In [1]:
%pip install --upgrade luxai-s3

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Note: you may need to restart the kernel to use updated packages.


In [2]:
from luxai_s3.wrappers import LuxAIS3GymEnv, RecordEpisode
import numpy as np

np.set_printoptions(linewidth=200)

In [3]:
env = RecordEpisode(
    LuxAIS3GymEnv(numpy_output=True), save_on_close=True, save_on_reset=True, save_dir="replays"
)

In [4]:
obs, info = env.reset()

# obs

In [5]:
obs.keys()

dict_keys(['player_0', 'player_1'])

In [6]:
obs_player_0 = obs['player_0']
type(obs_player_0)

dict

In [7]:
obs_player_0.keys()

dict_keys(['units', 'units_mask', 'sensor_mask', 'map_features', 'relic_nodes', 'relic_nodes_mask', 'team_points', 'team_wins', 'steps', 'match_steps'])

In [8]:
for i, key in enumerate(obs_player_0.keys()):
    print(i)
    print(key)

0
units
1
units_mask
2
sensor_mask
3
map_features
4
relic_nodes
5
relic_nodes_mask
6
team_points
7
team_wins
8
steps
9
match_steps


In [9]:
obs_player_0_units = obs_player_0['units']
type(obs_player_0_units)

dict

In [10]:
obs_player_0_units.keys()

dict_keys(['position', 'energy'])

In [11]:
obs_player_0_units_position = obs_player_0_units['position']
type(obs_player_0_units_position)

numpy.ndarray

In [12]:
obs_player_0_units_position.shape

(2, 16, 2)

In [13]:
obs_player_0_units_position

array([[[-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1]],

       [[-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1]]], dtype=int16)

In [14]:
obs_player_0_units_position[0][0]

array([-1, -1], dtype=int16)

In [15]:
obs_player_0_units_position[0][0]

array([-1, -1], dtype=int16)

In [16]:
obs_player_0_units_energy = obs_player_0_units['energy']
type(obs_player_0_units_energy)

numpy.ndarray

In [17]:
obs_player_0_units_energy.shape

(2, 16)

In [18]:
obs_player_0_units_energy

array([[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]], dtype=int16)

In [19]:
obs_player_0_units_mask = obs_player_0['units_mask']
type(obs_player_0_units_mask)

numpy.ndarray

In [20]:
obs_player_0_units_mask.shape

(2, 16)

In [21]:
obs_player_0_units_mask

array([[False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]])

In [22]:
obs_player_0_sensor_mask = obs_player_0['sensor_mask']
type(obs_player_0_sensor_mask)

numpy.ndarray

In [23]:
obs_player_0_sensor_mask.shape

(24, 24)

In [24]:
obs_player_0_sensor_mask

array([[False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, Fa

In [25]:
obs_player_0_map_features = obs_player_0['map_features']
type(obs_player_0_map_features)

dict

In [26]:
obs_player_0_map_features.keys()

dict_keys(['energy', 'tile_type'])

In [27]:
obs_player_0_map_features_energy = obs_player_0_map_features['energy']
type(obs_player_0_map_features_energy)

numpy.ndarray

In [28]:
obs_player_0_map_features_energy.shape

(24, 24)

In [29]:
obs_player_0_map_features_energy

array([[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,

In [30]:
obs_player_0_map_features_tile_type = obs_player_0_map_features['tile_type']
type(obs_player_0_map_features_tile_type)

numpy.ndarray

In [31]:
obs_player_0_map_features_tile_type.shape

(24, 24)

In [32]:
obs_player_0_map_features_tile_type

array([[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,

In [33]:
obs_player_0_relic_nodes = obs_player_0['relic_nodes']
type(obs_player_0_relic_nodes)

numpy.ndarray

In [34]:
obs_player_0_relic_nodes.shape

(6, 2)

In [35]:
obs_player_0_relic_nodes

array([[-1, -1],
       [-1, -1],
       [-1, -1],
       [-1, -1],
       [-1, -1],
       [-1, -1]], dtype=int16)

In [36]:
obs_player_0_relic_nodes_mask = obs_player_0['relic_nodes_mask']
type(obs_player_0_relic_nodes_mask)

numpy.ndarray

In [37]:
obs_player_0_relic_nodes_mask.shape

(6,)

In [38]:
obs_player_0_relic_nodes_mask

array([False, False, False, False, False, False])

In [39]:
obs_player_0_relic_nodes_mask.sum()

0

In [40]:
obs_player_0_relic_nodes_mask.size

6

In [41]:
for i in range(obs_player_0_relic_nodes_mask.size):
    if obs_player_0_relic_nodes_mask[i]:
        print(f"Relic node {i} is visible")
    else:
        print(f"Relic node {i} is not visible")

Relic node 0 is not visible
Relic node 1 is not visible
Relic node 2 is not visible
Relic node 3 is not visible
Relic node 4 is not visible
Relic node 5 is not visible


In [42]:
obs_player_0_steps = obs_player_0['steps']
type(obs_player_0_steps)

numpy.ndarray

In [43]:
obs_player_0_steps.shape

()

In [44]:
obs_player_0_steps

array(0, dtype=int32)

In [45]:
obs_player_0_match_steps = obs_player_0['match_steps']
type(obs_player_0_match_steps)

numpy.ndarray

In [46]:
obs_player_0_match_steps.shape

()

In [47]:
obs_player_0_match_steps

array(0, dtype=int32)

# info

In [48]:
type(info)

dict

In [49]:
info.keys()

dict_keys(['params', 'full_params', 'state'])

In [50]:
info_params = info['params']
type(info_params)

dict

In [51]:
info_params.keys()

dict_keys(['max_units', 'match_count_per_episode', 'max_steps_in_match', 'map_height', 'map_width', 'num_teams', 'unit_move_cost', 'unit_sap_cost', 'unit_sap_range', 'unit_sensor_range'])

In [52]:
info_params_max_units = info_params['max_units']
type(info_params_max_units)

int

In [53]:
info_params_max_units

16

In [54]:
info_params_match_count_per_episode = info_params['match_count_per_episode']
type(info_params_match_count_per_episode)

int

In [55]:
info_params_match_count_per_episode

5

In [56]:
info_params_max_steps_in_match = info_params['max_steps_in_match']
type(info_params_max_steps_in_match)

int

In [57]:
info_params_max_steps_in_match

100

In [58]:
info_params_map_height = info_params['map_height']
type(info_params_map_height)

int

In [59]:
info_params_map_height

24

In [60]:
info_params_map_width = info_params['map_width']
type(info_params_map_width)

int

In [61]:
info_params_map_width

24

In [62]:
info_params_num_teams = info_params['num_teams']
type(info_params_num_teams)

int

In [63]:
info_params_num_teams

2

In [64]:
info_params_unit_move_cost = info_params['unit_move_cost']
type(info_params_unit_move_cost)

int

In [65]:
info_params_unit_move_cost

4

In [66]:
info_params_unit_sap_cost = info_params['unit_sap_cost']
type(info_params_unit_sap_cost)

int

In [67]:
info_params_unit_sap_cost

45

In [68]:
info_params_unit_sap_range = info_params['unit_sap_range']
type(info_params_unit_sap_range)

int

In [69]:
info_params_unit_sap_range

3

In [70]:
info_params_unit_sensor_range = info_params['unit_sensor_range']
type(info_params_unit_sensor_range)

int

In [71]:
info_params_unit_sensor_range

2

In [72]:
info_full_params = info['full_params']
type(info_full_params)

dict

In [73]:
info_full_params.keys()

dict_keys(['max_steps_in_match', 'map_type', 'map_width', 'map_height', 'num_teams', 'match_count_per_episode', 'max_units', 'init_unit_energy', 'min_unit_energy', 'max_unit_energy', 'unit_move_cost', 'spawn_rate', 'unit_sap_cost', 'unit_sap_range', 'unit_sap_dropoff_factor', 'unit_energy_void_factor', 'max_energy_nodes', 'max_energy_per_tile', 'min_energy_per_tile', 'max_relic_nodes', 'relic_config_size', 'fog_of_war', 'unit_sensor_range', 'nebula_tile_vision_reduction', 'nebula_tile_energy_reduction', 'nebula_tile_drift_speed', 'energy_node_drift_speed', 'energy_node_drift_magnitude'])

In [74]:
for key in info_full_params.keys():
    print(key)
    print(type(info_full_params[key]))
    print(info_full_params[key])    

max_steps_in_match
<class 'int'>
100
map_type
<class 'int'>
1
map_width
<class 'int'>
24
map_height
<class 'int'>
24
num_teams
<class 'int'>
2
match_count_per_episode
<class 'int'>
5
max_units
<class 'int'>
16
init_unit_energy
<class 'int'>
100
min_unit_energy
<class 'int'>
0
max_unit_energy
<class 'int'>
400
unit_move_cost
<class 'int'>
4
spawn_rate
<class 'int'>
3
unit_sap_cost
<class 'int'>
45
unit_sap_range
<class 'int'>
3
unit_sap_dropoff_factor
<class 'float'>
1.0
unit_energy_void_factor
<class 'float'>
0.0625
max_energy_nodes
<class 'int'>
6
max_energy_per_tile
<class 'int'>
20
min_energy_per_tile
<class 'int'>
-20
max_relic_nodes
<class 'int'>
6
relic_config_size
<class 'int'>
5
fog_of_war
<class 'bool'>
True
unit_sensor_range
<class 'int'>
2
nebula_tile_vision_reduction
<class 'int'>
5
nebula_tile_energy_reduction
<class 'int'>
5
nebula_tile_drift_speed
<class 'float'>
0.10000000149011612
energy_node_drift_speed
<class 'float'>
0.05000000074505806
energy_node_drift_magnitude
<

In [75]:
info_state = info['state']
type(info_state)

luxai_s3.state.EnvState

In [76]:
dir(info_state)

['__annotations__',
 '__class__',
 '__dataclass_fields__',
 '__dataclass_params__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__match_args__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_flax_dataclass',
 'energy_node_fns',
 'energy_nodes',
 'energy_nodes_mask',
 'map_features',
 'match_steps',
 'relic_node_configs',
 'relic_nodes',
 'relic_nodes_map_weights',
 'relic_nodes_mask',
 'relic_spawn_schedule',
 'replace',
 'sensor_mask',
 'steps',
 'team_points',
 'team_wins',
 'units',
 'units_mask',
 'vision_power_map']

In [77]:
info_state.__dict__.keys()

dict_keys(['units', 'units_mask', 'energy_nodes', 'energy_node_fns', 'energy_nodes_mask', 'relic_nodes', 'relic_node_configs', 'relic_nodes_mask', 'relic_nodes_map_weights', 'relic_spawn_schedule', 'map_features', 'sensor_mask', 'vision_power_map', 'team_points', 'team_wins', 'steps', 'match_steps'])

In [78]:
info_state.units.position.shape

(2, 16, 2)

# Agent test and next steps

In [79]:
from lux.utils import direction_to
import sys
import numpy as np
class Agent():
    def __init__(self, player: str, env_cfg) -> None:
        self.player = player
        self.opp_player = "player_1" if self.player == "player_0" else "player_0"
        self.team_id = 0 if self.player == "player_0" else 1
        self.opp_team_id = 1 if self.team_id == 0 else 0
        np.random.seed(0)
        self.env_cfg = env_cfg
        
        self.relic_node_positions = []
        self.discovered_relic_nodes_ids = set()
        self.unit_explore_locations = dict()

    def act(self, step: int, obs, remainingOverageTime: int = 60):
        """implement this function to decide what actions to send to each available unit. 
        
        step is the current timestep number of the game starting from 0 going up to max_steps_in_match * match_count_per_episode - 1.
        """
        unit_mask = np.array(obs["units_mask"][self.team_id]) # shape (max_units, )
        unit_positions = np.array(obs["units"]["position"][self.team_id]) # shape (max_units, 2)
        unit_energys = np.array(obs["units"]["energy"][self.team_id]) # shape (max_units, 1)
        observed_relic_node_positions = np.array(obs["relic_nodes"]) # shape (max_relic_nodes, 2)
        observed_relic_nodes_mask = np.array(obs["relic_nodes_mask"]) # shape (max_relic_nodes, )
        team_points = np.array(obs["team_points"]) # points of each team, team_points[self.team_id] is the points of the your team
        
        # ids of units you can control at this timestep
        available_unit_ids = np.where(unit_mask)[0]
        # visible relic nodes
        visible_relic_node_ids = set(np.where(observed_relic_nodes_mask)[0])
        
        actions = np.zeros((self.env_cfg["max_units"], 3), dtype=int)


        # basic strategy here is simply to have some units randomly explore and some units collecting as much energy as possible
        # and once a relic node is found, we send all units to move randomly around the first relic node to gain points
        # and information about where relic nodes are found are saved for the next match
        
        # save any new relic nodes that we discover for the rest of the game.
        for id in visible_relic_node_ids:
            if id not in self.discovered_relic_nodes_ids:
                self.discovered_relic_nodes_ids.add(id)
                self.relic_node_positions.append(observed_relic_node_positions[id])
            

        # unit ids range from 0 to max_units - 1
        for unit_id in available_unit_ids:
            unit_pos = unit_positions[unit_id]
            unit_energy = unit_energys[unit_id]
            if len(self.relic_node_positions) > 0:
                nearest_relic_node_position = self.relic_node_positions[0]
                manhattan_distance = abs(unit_pos[0] - nearest_relic_node_position[0]) + abs(unit_pos[1] - nearest_relic_node_position[1])
                
                # if close to the relic node we want to hover around it and hope to gain points
                if manhattan_distance <= 4:
                    random_direction = np.random.randint(0, 5)
                    actions[unit_id] = [random_direction, 0, 0]
                else:
                    # otherwise we want to move towards the relic node
                    actions[unit_id] = [direction_to(unit_pos, nearest_relic_node_position), 0, 0]
            else:
                # randomly explore by picking a random location on the map and moving there for about 20 steps
                if step % 20 == 0 or unit_id not in self.unit_explore_locations:
                    rand_loc = (np.random.randint(0, self.env_cfg["map_width"]), np.random.randint(0, self.env_cfg["map_height"]))
                    self.unit_explore_locations[unit_id] = rand_loc
                actions[unit_id] = [direction_to(unit_pos, self.unit_explore_locations[unit_id]), 0, 0]
        return actions

In [80]:
agent0 = Agent("player_0", info_params)
agent1 = Agent("player_1", info_params)

In [81]:
actions0 = agent0.act(obs['player_0']['steps'], obs['player_0'])
actions1 = agent1.act(obs['player_1']['steps'], obs['player_1'])

In [82]:
actions0

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [83]:
next_obs, reward, terminated, truncated, info = env.step({
    "player_0": actions0,
    "player_1": actions1
})

In [84]:
next_obs.keys()

dict_keys(['player_0', 'player_1'])

In [85]:
next_obs['player_0'].keys()

dict_keys(['units', 'units_mask', 'sensor_mask', 'map_features', 'relic_nodes', 'relic_nodes_mask', 'team_points', 'team_wins', 'steps', 'match_steps'])

In [86]:
reward

{'player_0': array(0, dtype=int32), 'player_1': array(0, dtype=int32)}

In [87]:
terminated

{'player_0': array(False), 'player_1': array(False)}

In [88]:
truncated

{'player_0': array(False), 'player_1': array(False)}

In [89]:
info.keys()

dict_keys(['discount', 'final_observation', 'final_state', 'player_0', 'player_1'])

In [90]:
info['discount']

Array(1., dtype=float32, weak_type=True)

In [91]:
info['final_observation']

{'player_0': EnvObs(units=UnitState(position=Array([[[ 0,  0],
         [-1, -1],
         [-1, -1],
         [-1, -1],
         [-1, -1],
         [-1, -1],
         [-1, -1],
         [-1, -1],
         [-1, -1],
         [-1, -1],
         [-1, -1],
         [-1, -1],
         [-1, -1],
         [-1, -1],
         [-1, -1],
         [-1, -1]],
 
        [[-1, -1],
         [-1, -1],
         [-1, -1],
         [-1, -1],
         [-1, -1],
         [-1, -1],
         [-1, -1],
         [-1, -1],
         [-1, -1],
         [-1, -1],
         [-1, -1],
         [-1, -1],
         [-1, -1],
         [-1, -1],
         [-1, -1],
         [-1, -1]]], dtype=int16), energy=Array([[100,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
        [ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1]], dtype=int16)), units_mask=Array([[ True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, Fal

In [92]:
info['final_state']

EnvState(units=UnitState(position=Array([[[ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0]],

       [[23, 23],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0]]], dtype=int16), energy=Array([[[100],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0]],

       [[100],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
   

In [93]:
info['player_0']

{}

In [94]:
info['player_1']

{}

In [95]:
next_obs['player_0']['team_points']

array([0, 0], dtype=int32)

In [96]:
next_obs['player_1']['team_points']

array([0, 0], dtype=int32)

In [97]:
next_obs['player_0']['steps']

array(1, dtype=int32)

In [98]:
next_obs['player_1']['steps']

array(1, dtype=int32)

In [99]:
actions0 = agent0.act(next_obs['player_0']['steps'], next_obs['player_0'])
actions1 = agent1.act(next_obs['player_1']['steps'], next_obs['player_1'])

In [100]:
actions0

array([[3, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [101]:
info_params

{'max_units': 16,
 'match_count_per_episode': 5,
 'max_steps_in_match': 100,
 'map_height': 24,
 'map_width': 24,
 'num_teams': 2,
 'unit_move_cost': 4,
 'unit_sap_cost': 45,
 'unit_sap_range': 3,
 'unit_sensor_range': 2}

In [102]:
print("Tile type: \n", next_obs['player_0']['map_features']['tile_type'])

Tile type: 
 [[ 0  0  0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [ 0  0  0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [ 0  0  0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -

In [103]:
actions0

array([[3, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [104]:
next_obs['player_0']['map_features']['tile_type'].T

array([[ 0,  0,  0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [ 0,  0,  0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [ 0,  0,  0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,

In [105]:
next_obs['player_0']['units']['position']

array([[[ 0,  0],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1]],

       [[-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1]]], dtype=int16)

In [106]:
next_obs['player_0']['sensor_mask'].T

array([[ True,  True,  True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
       [ True,  True,  True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
       [ True,  True,  True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, Fa

In [107]:
next_obs, reward, terminated, truncated, info = env.step({
    "player_0": actions0,
    "player_1": actions1
})

print("Reward: ", reward)
print("Player 0 points: ", next_obs['player_0']['team_points'])
print("Player 1 points: ", next_obs['player_1']['team_points'])
print("Player 0 steps: ", next_obs['player_0']['steps'])
print("Player 1 steps: ", next_obs['player_1']['steps'])

actions0 = agent0.act(next_obs['player_0']['steps'], next_obs['player_0'])
actions1 = agent1.act(next_obs['player_1']['steps'], next_obs['player_1'])

#print(actions0)

print("Tile type: \n", next_obs['player_0']['map_features']['tile_type'].T)

Reward:  {'player_0': array(0, dtype=int32), 'player_1': array(0, dtype=int32)}
Player 0 points:  [0 0]
Player 1 points:  [0 0]
Player 0 steps:  2
Player 1 steps:  2
Tile type: 
 [[ 0  0  0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [ 0  0  0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [ 0  0  0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [ 0  0  0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 

In [108]:
next_obs['player_0']['units']['position']

array([[[ 0,  1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1]],

       [[-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1]]], dtype=int16)

In [104]:
info.keys()

dict_keys(['discount', 'final_observation', 'final_state', 'player_0', 'player_1'])

In [105]:
next_obs.keys()

dict_keys(['player_0', 'player_1'])

In [106]:
next_obs['player_0'].keys()

dict_keys(['units', 'units_mask', 'sensor_mask', 'map_features', 'relic_nodes', 'relic_nodes_mask', 'team_points', 'team_wins', 'steps', 'match_steps'])

# Loop

In [ ]:
obs_all, info = env.reset()
env_cfg = info['params']

In [ ]:
agent0 = Agent("player_0", env_cfg)
agent1 = Agent("player_1", env_cfg)

In [ ]:
actions0 = agent0.act(obs_all['player_0']['steps'], obs_all['player_0'])
actions1 = agent1.act(obs_all['player_1']['steps'], obs_all['player_1'])

In [ ]:
obs_all['player_0']['steps']

In [ ]:
obs_all['player_0']['match_steps']

In [ ]:
obs_all['player_0']['units']['position']

In [ ]:
obs_all['player_0']['team_points']

In [ ]:
for i in range(1000):
    next_obs, reward, terminated, truncated, info = env.step({
        "player_0": actions0,
        "player_1": actions1
    })

    print("Reward: ", reward)
    
    print("Player 0 points: ", next_obs['player_0']['team_points'])
    print("Player 1 points: ", next_obs['player_1']['team_points'])
    print("Player 0 steps: ", next_obs['player_0']['steps'])
    print("Player 0 match steps: ", next_obs['player_0']['match_steps'])
    print("Player 1 steps: ", next_obs['player_1']['steps'])
    print("Player 1 match steps: ", next_obs['player_1']['match_steps'])
    print("Player 0 units position: ", next_obs['player_0']['units']['position'])
    print("Player 1 units position: ", next_obs['player_1']['units']['position'])

    actions0 = agent0.act(next_obs['player_0']['steps'], next_obs['player_0'])
    actions1 = agent1.act(next_obs['player_1']['steps'], next_obs['player_1'])

    #print(actions0)

    print("Player 0 tile type: \n", next_obs['player_0']['map_features']['tile_type'])